/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.Interfaz;

/**
 *
 * @author linco
 */
public class vistaCuadricula extends javax.swing.JPanel {

    private java.util.List<Producto> productos;
    private int productosPorPagina = 10; // 5 columnas x 2 filas
    private int paginaActual = 1;
    private int totalPaginas = 1;

    /**
     * Creates new form vistaCuadricula
     */
    public vistaCuadricula() {
        initComponents();

        /*---------------------------------------*/
        // Simular productos (luego reemplazas con tu consulta SQL)
        java.util.List<Producto> mock = new java.util.ArrayList<>();
        for (int i = 1; i <= 25; i++) {
            mock.add(new Producto("Producto " + i, "Desc " + i));
        }

        cargarProductos(mock);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaLista = new javax.swing.JPanel();
        txtLista = new javax.swing.JLabel();
        ScrollCuadricula = new javax.swing.JScrollPane();
        contenedorCuadricula = new javax.swing.JPanel();
        panelPaginacion = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        txtPaginaActual = new javax.swing.JLabel();

        vistaLista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        vistaLista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtLista.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        txtLista.setIcon(new javax.swing.ImageIcon("C:\\Users\\linco\\OneDrive\\Documentos\\NeumaControl\\NeumaControl\\NeumaControl\\Imagenes\\Iconos\\cuadricula.png")); // NOI18N
        txtLista.setText("Lista");

        javax.swing.GroupLayout vistaListaLayout = new javax.swing.GroupLayout(vistaLista);
        vistaLista.setLayout(vistaListaLayout);
        vistaListaLayout.setHorizontalGroup(
            vistaListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtLista, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );
        vistaListaLayout.setVerticalGroup(
            vistaListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtLista, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        contenedorCuadricula.setLayout(new java.awt.GridLayout(0, 5, 10, 10));
        ScrollCuadricula.setViewportView(contenedorCuadricula);

        btnAnterior.setText("Anterior <<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText(">> Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        txtPaginaActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPaginaActual.setText("jLabel1");

        javax.swing.GroupLayout panelPaginacionLayout = new javax.swing.GroupLayout(panelPaginacion);
        panelPaginacion.setLayout(panelPaginacionLayout);
        panelPaginacionLayout.setHorizontalGroup(
            panelPaginacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaginacionLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(btnAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPaginaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSiguiente)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        panelPaginacionLayout.setVerticalGroup(
            panelPaginacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaginacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnAnterior)
                .addComponent(btnSiguiente)
                .addComponent(txtPaginaActual))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollCuadricula)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vistaLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelPaginacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vistaLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(ScrollCuadricula, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPaginacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if (paginaActual > 1) {
            paginaActual--;
            mostrarPagina(paginaActual);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if (paginaActual < totalPaginas) {
            paginaActual++;
            mostrarPagina(paginaActual);
        }

    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void cargarProductos(java.util.List<Producto> lista) {
        this.productos = lista;
        this.totalPaginas = (int) Math.ceil((double) productos.size() / productosPorPagina);
        mostrarPagina(paginaActual);
    }

    private void mostrarPagina(int pagina) {
        contenedorCuadricula.removeAll();

        int inicio = (pagina - 1) * productosPorPagina;
        int fin = Math.min(inicio + productosPorPagina, productos.size());

        for (int i = inicio; i < fin; i++) {
            Producto p = productos.get(i);
            contenedorCuadricula.add(crearTarjetaProducto(p));
        }

        txtPaginaActual.setText("Página " + pagina + " de " + totalPaginas);
        contenedorCuadricula.revalidate();
        contenedorCuadricula.repaint();
    }

    private javax.swing.JPanel crearTarjetaProducto(Producto p) {
        javax.swing.JPanel tarjeta = new javax.swing.JPanel();
        tarjeta.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));
        tarjeta.setPreferredSize(new java.awt.Dimension(100, 100));
        tarjeta.setLayout(new java.awt.BorderLayout());

        javax.swing.JLabel nombre = new javax.swing.JLabel(p.getNombre(), javax.swing.SwingConstants.CENTER);
        javax.swing.JLabel desc = new javax.swing.JLabel(p.getDescripcion(), javax.swing.SwingConstants.CENTER);

        tarjeta.add(nombre, java.awt.BorderLayout.NORTH);
        tarjeta.add(desc, java.awt.BorderLayout.CENTER);

        return tarjeta;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollCuadricula;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JPanel contenedorCuadricula;
    private javax.swing.JPanel panelPaginacion;
    private javax.swing.JLabel txtLista;
    private javax.swing.JLabel txtPaginaActual;
    private javax.swing.JPanel vistaLista;
    // End of variables declaration//GEN-END:variables
}
